Console.ForegroundColor = (ConsoleColor)12;
Console.WriteLine("HINO DO SÂO PAULO FUTEBOL CLUBE");
Console.ResetColor();
Console.WriteLine("Salve o tricolor paulista");
Thread.Sleep(1000);
Console.WriteLine("Amado clube brasileiro");
Thread.Sleep(1000);
Console.WriteLine("Tu és forte, tu és grande");
Thread.Sleep(1000);
Console.WriteLine("Dentre os grandes és o primeiro");
Thread.Sleep(1000);
Console.WriteLine("Tu és forte, tu és grande");
Thread.Sleep(1000);
Console.WriteLine("Dentre os grandes és o primeiro");
Thread.Sleep(1000);
Console.ForegroundColor = (ConsoleColor)12;
Console.WriteLine("Ó tricolor");
Thread.Sleep(1000);
Console.WriteLine("Clube bem amado");
Thread.Sleep(1000);
Console.WriteLine("As tuas glórias");
Thread.Sleep(1000);
Console.WriteLine("Vêm do passado");
Thread.Sleep(1000);
Console.WriteLine("Ó tricolor");
Thread.Sleep(1000);
Console.WriteLine("Clube bem amado");
Thread.Sleep(1000);
Console.WriteLine("As tuas glórias");
Thread.Sleep(1000);
Console.WriteLine("Vêm do passado");
Thread.Sleep(1000);
Console.ResetColor();

Console.WriteLine("São teus guias brasileiros");
Thread.Sleep(1000);
Console.WriteLine("Que te amam ternamente");
Thread.Sleep(1000);
Console.WriteLine("De São Paulo tens o nome");
Thread.Sleep(1000);
Console.WriteLine("Que ostentas dignamente");
Thread.Sleep(1000);
Console.WriteLine("De São Paulo tens o nome");
Thread.Sleep(1000);
Console.WriteLine("Que ostentas dignamente");
Thread.Sleep(1000);